info:
  app:
    name: nb-web
    description: www.nb.no

server:
  port: 7070


zuul:
  routes:
    nb-api:
      path: /api/**
      url: http://cp1.nb.no:8765/

---

spring:
  profiles: test

zuul:
routes:
  nb-api:
    path: /api/**
    url: http://cp1.nb.no:8765/

---

spring:
  profiles: prod

zuul:
  routes:
    nb-api:
      path: /api/**
      url: http://api.nb.no:8765/
